/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WurmSleepBonusNotifier;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class LibraryTest {
}
